// sessionActions

export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CONFIRMATION_ERROR = 'LOGIN_CONFIRMATION_ERROR';
export const RESEND_CONFIRMATION_EMAIL_FETCH = 'RESEND_CONFIRMATION_EMAIL_FETCH';
export const RESEND_CONFIRMATION_EMAIL_SUCCESS = 'RESEND_CONFIRMATION_EMAIL_SUCCESS';
export const RESEND_CONFIRMATION_EMAIL_ERROR = 'RESEND_CONFIRMATION_EMAIL_ERROR';
export const REGISTER_FETCH = 'REGISTER_FETCH';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CONFIRM_REGISTRATION_FETCH = 'CONFIRM_REGISTRATION_FETCH';
export const CONFIRM_REGISTRATION_SUCCESS = 'CONFIRM_REGISTRATION_SUCCESS';
export const CONFIRM_REGISTRATION_ERROR = 'CONFIRM_REGISTRATION_ERROR';
export const PASSWORD_RECOVERY_FETCH = 'PASSWORD_RECOVERY_FETCH';
export const PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS';
export const PASSWORD_RECOVERY_ERROR = 'PASSWORD_RECOVERY_ERROR';
export const PASSWORD_RESET_FETCH = 'PASSWORD_RESET_FETCH';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

// loginActions

export const LOGIN_VIEW_CHANGE = 'LOGIN_VIEW_CHANGE';

// forgotActions

export const FORGOT_VIEW_CHANGE = 'FORGOT_VIEW_CHANGE';

// registerActions

export const REGISTER_VIEW_CHANGE = 'REGISTER_VIEW_CHANGE';

// navigationActions

export const TOGGLE_MENU = 'TOGGLE_MENU';

// storeActions

export const SET_STORE_NAME = 'SET_STORE_NAME';

// cartActions

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';
export const UPDATE_PRODUCT_DISPLAY_QUANTITY = 'UPDATE_PRODUCT_DISPLAY_QUANTITY';
export const RESET_PRODUCT_QUANTITY = 'RESET_PRODUCT_QUANTITY';

// checkoutActions

export const GET_CHECKOUT_ADDRESSES_FETCH = 'GET_CHECKOUT_ADDRESSES_FETCH';
export const GET_CHECKOUT_ADDRESSES_SUCCESS = 'GET_CHECKOUT_ADDRESSES_SUCCESS';
export const GET_CHECKOUT_ADDRESSES_ERROR = 'GET_CHECKOUT_ADDRESSES_ERROR';
export const ADD_CHECKOUT_ADDRESS_FETCH = 'ADD_CHECKOUT_ADDRESS_FETCH';
export const ADD_CHECKOUT_ADDRESS_SUCCESS = 'ADD_CHECKOUT_ADDRESS_SUCCESS';
export const ADD_CHECKOUT_ADDRESS_ERROR = 'ADD_CHECKOUT_ADDRESS_ERROR';
export const CHANGE_CHECKOUT_ADDRESS = 'CHANGE_CHECKOUT_ADDRESS';
export const GET_SHIPPING_COST_FETCH = 'GET_SHIPPING_COST_FETCH';
export const GET_SHIPPING_COST_SUCCESS = 'GET_SHIPPING_COST_SUCCESS';
export const GET_SHIPPING_COST_ERROR = 'GET_SHIPPING_COST_ERROR';
export const GET_CHECKOUT_CARDS_FETCH = 'GET_CHECKOUT_CARDS_FETCH';
export const GET_CHECKOUT_CARDS_SUCCESS = 'GET_CHECKOUT_CARDS_SUCCESS';
export const GET_CHECKOUT_CARDS_ERROR = 'GET_CHECKOUT_CARDS_ERROR';
export const ADD_CHECKOUT_CARD_FETCH = 'ADD_CHECKOUT_CARD_FETCH';
export const ADD_CHECKOUT_CARD_SUCCESS = 'ADD_CHECKOUT_CARD_SUCCESS';
export const ADD_CHECKOUT_CARD_ERROR = 'ADD_CHECKOUT_CARD_ERROR';
export const CHANGE_CHECKOUT_CARD = 'CHANGE_CHECKOUT_CARD';
export const CHANGE_ACTIVE_SECTION = 'CHANGE_ACTIVE_SECTION';
export const PLACE_ORDER_FETCH = 'PLACE_ORDER_FETCH';
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR';
export const CONFIRM_ORDER_FETCH = 'CONFIRM_ORDER_FETCH';
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
export const CONFIRM_ORDER_ERROR = 'CONFIRM_ORDER_ERROR';
export const OPEN_CHECKOUT_DIALOG = 'OPEN_CHECKOUT_DIALOG';
export const CLOSE_CHECKOUT_DIALOG = 'CLOSE_CHECKOUT_DIALOG';
export const EXIT_CHECKOUT_DIALOG = 'EXIT_CHECKOUT_DIALOG';

// productsActions

export const GET_PRODUCTS_FETCH = 'GET_PRODUCTS_FETCH';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const OPEN_PRODUCT_DIALOG = 'OPEN_PRODUCT_DIALOG';
export const CLOSE_PRODUCT_DIALOG = 'CLOSE_PRODUCT_DIALOG';
export const EXIT_PRODUCT_DIALOG = 'EXIT_PRODUCT_DIALOG';

// addressActions

export const GET_ADDRESSES_FETCH = 'GET_ADDRESSES_FETCH';
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';
export const GET_ADDRESSES_ERROR = 'GET_ADDRESSES_ERROR';
export const ADD_ADDRESS_FETCH = 'ADD_ADDRESS_FETCH';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_ERROR = 'ADD_ADDRESS_ERROR'; 
export const UPDATE_ADDRESS_FETCH = 'UPDATE_ADDRESS_FETCH';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_ERROR = 'UPDATE_ADDRESS_ERROR';
export const DELETE_ADDRESS_FETCH = 'DELETE_ADDRESS_FETCH';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_ERROR = 'DELETE_ADDRESS_ERROR';
export const OPEN_ADDRESS_DIALOG = 'OPEN_ADDRESS_DIALOG';
export const CLOSE_ADDRESS_DIALOG = 'CLOSE_ADDRESS_DIALOG';
export const EXIT_ADDRESS_DIALOG = 'EXIT_ADDRESS_DIALOG';

// cardsActions

export const GET_CARDS_FETCH = 'GET_CARDS_FETCH';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_ERROR = 'GET_CARDS_ERROR';
export const ADD_CARD_FETCH = 'ADD_CARD_FETCH';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_ERROR = 'ADD_CARD_ERROR';
export const DELETE_CARD_FETCH = 'DELETE_CARD_FETCH';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_ERROR = 'DELETE_CARD_ERROR';
export const SET_PRIMARY_CARD_SUCCESS = 'SET_PRIMARY_CARD_SUCCESS';
export const OPEN_CARDS_DIALOG = 'OPEN_CARDS_DIALOG';
export const CLOSE_CARDS_DIALOG = 'CLOSE_CARDS_DIALOG';
export const EXIT_CARDS_DIALOG = 'EXIT_CARDS_DIALOG';

// ordersActions

export const GET_ORDERS_FETCH = 'GET_ORDERS_FETCH';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

// snackbarsActions

export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const EXIT_SNACKBAR = 'EXIT_SNACKBAR';